CONFIG_ZMK_BLE_CLEAR_BONDS_ON_START=n

CONFIG_BT_SETTINGS=y
CONFIG_FLASH=y
CONFIG_FLASH_PAGE_LAYOUT=y
CONFIG_NVS=y
CONFIG_SETTINGS=y

# Go idle after 1 minute 30 seconds
CONFIG_ZMK_IDLE_TIMEOUT=90000

# Go to deep sleep after 5 minutes of inactivity
CONFIG_ZMK_IDLE_SLEEP_TIMEOUT=300000

# Enable sleep
CONFIG_ZMK_SLEEP=y
