CONFIG_ZMK_BLE_CLEAR_BONDS_ON_START=n
CONFIG_BT_SETTINGS=y
CONFIG_FLASH=y
CONFIG_FLASH_PAGE_LAYOUT=y
CONFIG_NVS=y
CONFIG_SETTINGS=y
CONFIG_ZMK_IDLE_TIMEOUT=6000
CONFIG_ZMK_IDLE_SLEEP_TIMEOUT=30000
CONFIG_ZMK_SLEEP=y
CONFIG_ZMK_PM_SOFT_OFF=y
